apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: cl
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cl 
    server: {{ .Values.spec.destination.server }}
  project: cl 
  source:
    path: apps/app1
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
