apiVersion: v1
kind: Namespace
metadata:
  name: chile 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: colombia 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
